[package]
name = "messages"
version = "0.1.0"
authors = ["dongfeng <18510416169@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elements = {path = "../elements"}
byteorder = "1"
